repos:
-   repo: local
    hooks:
    - id: check-poetry
      name: poetry check
      description: Validates the structure of the pyproject.toml file
      entry: poetry check
      language: system
      pass_filenames: false
      files: ./pyproject.toml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: ./run-mypy
      language: python
      language_version: python3.8
      # trigger for commits changing Python files
      types: [python]
      # is only called once per commit
      require_serial: true
      # Print the number of files as a sanity-check
      verbose: true
