name: lint

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install packages
        run: |
          pip install flake8
          pip install isort
          pip install black

      - name: Run flake8
        run: flake8

      - name: Run isort
        run: isort --check-only --verbose nirwl_metacal/ tests/

      - name: Run black
        run: black --check --verbose --diff nirwl_metacal/ tests/
